#!/usr/bin/env python3
"""
Greenfield Project Quick Start Script

This script scaffolds and runs a new TeamAlpha project.
Usage: python3 quickstart.py --name my-project --template greenfield
"""

import os
import sys
import shutil
import argparse
from pathlib import Path
from datetime import datetime

def create_project(name: str, template: str = "greenfield"):
    """Create a new project from template."""
    
    base_path = Path(__file__).parent
    template_path = base_path / "projects" / f"{template}-starter"
    project_path = base_path / "projects" / name
    
    if not template_path.exists():
        print(f"❌ Template not found: {template_path}")
        return False
    
    if project_path.exists():
        print(f"❌ Project already exists: {project_path}")
        return False
    
    print(f"📦 Creating project: {name}")
    print(f"   From template: {template}")
    print(f"   Location: {project_path}\n")
    
    # Copy template
    try:
        shutil.copytree(template_path, project_path)
        print(f"✓ Project directory created")
    except Exception as e:
        print(f"❌ Failed to copy template: {e}")
        return False
    
    # Update project.yaml
    project_yaml = project_path / "project.yaml"
    if project_yaml.exists():
        with open(project_yaml, 'r') as f:
            content = f.read()
        
        # Replace placeholder with project name
        content = content.replace("blank-project", name)
        content = content.replace("0.1.0", "0.1.0")  # Keep version
        
        with open(project_yaml, 'w') as f:
            f.write(content)
        
        print(f"✓ Updated project.yaml")
    
    # Create initial README
    readme_content = f"""# {name.title()} - TeamAlpha Project

**Created**: {datetime.now().isoformat()}
**Status**: New project - in setup

## Quick Start

1. **Configure team**:
   ```bash
   nano team.yaml
   ```

2. **Define workflows**:
   ```bash
   nano workflows/__init__.py
   ```

3. **Add tools**:
   ```bash
   nano tools/__init__.py
   ```

4. **Run project**:
   ```bash
   python3 run.py
   ```

## Project Structure

- `project.yaml` - Project metadata
- `team.yaml` - Team definition
- `tools.yaml` - Tool registry
- `run.py` - Main entry point
- `workflows/` - Workflow definitions
- `tools/` - Custom tool implementations
- `output/` - Generated reports

## Next Steps

1. Read `README.md` for detailed setup
2. Check `../../../docs/TEAM_GUIDE.md` for framework guide
3. Review `../greenfield-starter/README.md` for template details

---
Generated by TeamAlpha Quickstart
"""
    
    with open(project_path / "QUICKSTART.md", 'w') as f:
        f.write(readme_content)
    
    print(f"✓ Created QUICKSTART.md")
    
    # Summary
    print(f"\n{'='*60}")
    print(f"✅ Project '{name}' created successfully!")
    print(f"{'='*60}\n")
    
    print("Next steps:")
    print(f"  1. cd projects/{name}")
    print(f"  2. nano team.yaml          # Configure your team")
    print(f"  3. nano project.yaml       # Update project metadata")
    print(f"  4. python3 run.py          # Run the project")
    print()
    print(f"For help, see:")
    print(f"  - {project_path}/README.md")
    print(f"  - ../../../docs/TEAM_GUIDE.md")
    
    return True


def main():
    parser = argparse.ArgumentParser(
        description="TeamAlpha Greenfield Project Quickstart"
    )
    parser.add_argument(
        '--name',
        required=True,
        help="Name of the new project"
    )
    parser.add_argument(
        '--template',
        default='greenfield',
        help="Template to use (default: greenfield)"
    )
    
    args = parser.parse_args()
    
    print("🚀 TeamAlpha Greenfield Project Quickstart")
    print("="*60)
    print()
    
    success = create_project(args.name, args.template)
    
    if not success:
        sys.exit(1)


if __name__ == "__main__":
    main()
